cnSystem_INTERFACE_ID_DEFINE(iCOMInterface)

cnSystem_INTERFACE_ID_DEFINE(iWaitableObject)
cnSystem_INTERFACE_ID_DEFINE(iWinThread)
cnSystem_INTERFACE_ID_DEFINE(iWinThreadPool)

cnSystem_INTERFACE_ID_DEFINE(iFileTime)
cnSystem_INTERFACE_ID_DEFINE(iWin32FileName)
cnSystem_INTERFACE_ID_DEFINE(iWinFileHandle)

cnSystem_INTERFACE_ID_DEFINE(iWinSocketMulticastAddress)

cnSystem_INTERFACE_ID_DEFINE(iWindow)
cnSystem_INTERFACE_ID_DEFINE(iWindowHandleProperty)
cnSystem_INTERFACE_ID_DEFINE(iWindowClient)
cnSystem_INTERFACE_ID_DEFINE(iWindowFrame)
cnSystem_INTERFACE_ID_DEFINE(iMouseCursorSetter)
cnSystem_INTERFACE_ID_DEFINE(iWindowViewport)

cnSystem_INTERFACE_ID_DEFINE(iGDIBitmap)


cnSystem_INTERFACE_ID_DEFINE(iWaveFormat)
